name: "mobilenetv2_12"
platform: "onnxruntime_onnx"
max_batch_size: 64
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [ 10 ]  # Соответствует входной размерности модели
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 5 ]  # Соответствует выходной размерности модели
  }
]